# Generated by Django 5.1.1 on 2026-04-30 16:51

import django.core.validators
import reviews.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), reviews.validators.validate_year_not_future], verbose_name='Год выпуска'),
        ),
    ]
